<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IN-MH1DSW101410" name="testscripts.cap.CAPSetupBulkCustomerTransferScripts" tests="4" failures="0" timestamp="28 Nov 2018 05:53:51 GMT" time="205.501" errors="2">
  <testcase name="verifyBCTWhenSrcAndDestTerritoryIsSame" time="53.576" classname="testscripts.cap.CAPSetupBulkCustomerTransferScripts"/>
  <testcase name="verifyCreateBCTRequest" time="28.579" classname="testscripts.cap.CAPSetupBulkCustomerTransferScripts">
    <error type="java.lang.Throwable" message="Steps Failed (1)
(1)verify.VerificationError:expected [Search Customer] but found [Setup Bulk Customer Transfer Request]

Failure 1 of 1
verify.VerificationError: expected [Search Customer] but found [Setup Bulk Customer Transfer Request]">
      <![CDATA[java.lang.Throwable: Steps Failed (1)
(1)verify.VerificationError:expected [Search Customer] but found [Setup Bulk Customer Transfer Request]

Failure 1 of 1
verify.VerificationError: expected [Search Customer] but found [Setup Bulk Customer Transfer Request]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:167)
	at verify.Verify.verifyEquals(Verify.java:90)
	at testscripts.cap.CAPSetupBulkCustomerTransferScripts.verifyCreateBCTRequest(CAPSetupBulkCustomerTransferScripts.java:294)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyCreateBCTRequest -->
  <testcase name="verifySearchAndPerformBCTRequest" time="0.000" classname="testscripts.cap.CAPSetupBulkCustomerTransferScripts">
    <error type="java.lang.Throwable" message="Method CAPSetupBulkCustomerTransferScripts.verifySearchAndPerformBCTRequest(java.lang.String, java.lang.String)[pri:0, instance:testscripts.cap.CAPSetupBulkCustomerTransferScripts@fad74ee] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method CAPSetupBulkCustomerTransferScripts.verifySearchAndPerformBCTRequest(java.lang.String, java.lang.String)[pri:0, instance:testscripts.cap.CAPSetupBulkCustomerTransferScripts@fad74ee] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifySearchAndPerformBCTRequest -->
  <testcase name="verifyRemoveCustomersFromBCTRequest" time="123.346" classname="testscripts.cap.CAPSetupBulkCustomerTransferScripts"/>
</testsuite> <!-- testscripts.cap.CAPSetupBulkCustomerTransferScripts -->
